models:
  - id: 1
    name: openai-gpt4o
    provider: openai
    modelName: gpt-4o
    baseUrl: https://api.openai.com/v1
    apiKey: ${OPENAI_API_KEY}
    status: 1
    defaultParameters:
      temperature: 0.7
      maxTokens: 4096
    supportedParameters:
      - name: temperature
        type: number
        minValue: 0
        maxValue: 2
        defaultValue: 0.7
        required: false
        description: 采样温度
      - name: maxTokens
        type: number
        minValue: 1
        maxValue: 4096
        defaultValue: 1024
        required: false
        description: 最大输出token


