server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript
    min-response-size: 2048
nacos:
  server-addr: 127.0.0.1:8848

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      export:
        enabled: true
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        enabled: false
    logging:
      export:
        enabled: false
  opentelemetry:
    resource-attributes:
      service:
        # shouldn't be changed
        name: spring-ai-alibaba-studio
        version: 1.0
      deployment:
        environment: test
spring:
  ai:
    chat:
      client:
        observations:
          log-prompt: true
      observations:
        log-prompt: true
        log-completion: true
    image:
      observations:
        log-prompt: true
    vectorstore:
      observations:
        log-query-response: true
    alibaba:
      arms:
        enabled: true
        model:
          capture-input: true
          capture-output: true



  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
      enabled: true
  application:
    name: saa-studio

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/admin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: admin
    password: admin
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      filters: stat,wall,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          enabled: true
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true

  freemarker:
    cache: false
    charset: UTF-8
    suffix: .html
    enabled: true
    content-type: text/html
    template-loader-path: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.alibaba.cloud.ai.studio.admin.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    org.springframework.boot.autoconfigure: INFO
    org.springframework.boot.task: INFO

